### ISSUE TITLE
Guest Lecture List

### ISSUE THREAD

**Issue by LanceALaughlin** [decause/advfoss#100]
It would be nice to have a list of past guest lectures as well as future lecturers.

**Comment by f4ngy** [comment]
Adding to this, what if guest lectures were recorded and available online after the fact as well?

**Comment by decause** [comment]
We're working on a way to provide recorded lectures. If there were a dedicated extra "TAVA" (teaching audio-visual assistant) who could go through the trouble of editing the lecture footage and mic-ing the room, then perhaps this could work. For now, I'm too much of a one-man show to pull this off reasonable. Feel free to migrate the issue upstream to http://github.com/FOSSRIT/ofcourse.
