### ISSUE TITLE
Calendar with due dates and events

### ISSUE THREAD

**Issue by f4ngy** [decause/advfoss#104]
Calendar would contain things like
-rocpy
-hackathons
-homework assignment due dates
-etc.

Whether this is info entered manually, or something generated programmatically, I think this is a feature that is needed as we often have questions of "when is x" every class. (I myself am responsible for many of them :P )

**Comment by decause** [comment]
Calendaring is a non-trivial problem we are still working on. Perhaps migrate this ticket upstream as well? http://github.com/FOSSRIT/ofcourse
