### ISSUE TITLE
Start proposal: Project pools instead of set assignments

### ISSUE THREAD

**Issue by danShumway** [decause/advfoss#110]
Basically, we'd have a collection of different projects and assignments to work on, each worth a certain amount of points, and they would add up to our final grade.  We would choose between these different options and do enough of them to add up to a certain grade.

There are a number of advantages to this approach:
- A big part of FOSS is about finding niches to fill, but usually we end up doing very similar assignments in scope and size.
- It allows us to plan assignments around when we have time and to either bank work or procrastinate work accordingly, which helps a lot with getting release schedules set up.
- It forces us to be incredibly self-motivated.
- It would encourage us to branch out more and try different things.  It's easy with the current setup to do only the requirements and none of the extra stuff like lightning talks.
- It would almost instantly solve the "what grade do I currently have?" problem.
- It would look good on resumes.

The next step would be for me to actually sit down and write up something, which would be about the time when this could be theoretically closed down and I could make the proposal as a commit to the main syllabus.  There are a number of concerns with this method that I need to think about and address (getting certain assignments to be required, not allowing people to overload on one type of assignment, not allowing people to get all of them done and then sit around doing nothing, not allowing people to procrastinate on them, etc.. etc...), but I think there are potentially creative ways to deal with those problems without breaking the core mechanics of what the course would turn into.

**Comment by decause** [comment]
I like this idea, and it is very similar to @ralphbean 's approach in ADVFOSS back in the day. Perhaps we can play with this idea more in future iterations. Feel free to migrate this ticket to http://github.com/FOSSRIT/ofcourse.

**Comment by liam-middlebrook** [comment]
@decause this issue shouldn't be migrated to ofcourse because it's not really an issue with the courseware. I think this issue would be much better suited on [decause/hfoss](https://github.com/decause/hfoss) or [decause/advfoss](https://github.com/decause/advfoss)
