### ISSUE TITLE
Listing of ALL YAML keys, current and future, plus due dates

### ISSUE THREAD

**Issue by h2g2guy** [decause/advfoss#112]
Having a page dedicated to all the keys for all the assignments, along with their due dates, would be great, as it would both serve as a list of assignments for forgetful students (read: yours truly), as well as a roadmap for where the course will generally be going for future students.  

We already have this in part on the Participants page, but that's both slow to load and only helps for assignments you're already potentially late on.

I know we also sorta kinda have some of this functionality on the Assignments page, but I think it could be made a lot more helpful and robust (not to mention that it was sort of difficult to find the exact assignment you were looking for in HFOSS, because there were more assignments listed).

**Comment by decause** [comment]
This is closed by <code>assignments.yaml</code> in <code>ofcourse</code>
