### ISSUE TITLE
YAML Keys for Extra Credit

### ISSUE THREAD

**Issue by liam-middlebrook** [decause/advfoss#190]
@decause mentioned that we should set something for this.

**Comment by decause** [comment]
<code>hackathonN</code> for developer events.
<code>upstreamM</code> for patches accepted usptream.

**Comment by liam-middlebrook** [comment]
@decause I'm thinking in ofcourse that I'm going to change this pattern (for a release after this term is over) to something like the following.

```
# my fancy YAML and stuff
hw:
  firstflight: link
  # other homeworks
hackathons:
  - link to blog post for hackathon 0
  - link to blog post for hackathon 1
  - etc. . .
```

I think that having those as a YAML list is a lot more intuitive and really puts the YAML specification to good use.
