### ISSUE TITLE
Code Snippet Lightning Talks

### ISSUE THREAD

**Issue by liam-middlebrook** [decause/advfoss#200]
Have lightning talks with code snippets. Possibly github gists?

**Comment by decause** [comment]
@liam-middlebrook please migrate this ticket to ofcourse repo.

**Comment by liam-middlebrook** [comment]
I don't think this belongs on the ofcourse repo. If people want to add lightning talks they should add them to a course content repository. The talks would need to be put under `oer.yaml` in the root directory.
